version: '2'

services:
  bdocs:
    build: .
    volumes:
      - .:/usr/src/app/
    working_dir: /usr/src/app/docs
    command: make html
  vdocs:
    image: nginx
    ports:
      - '80'
    volumes:
      - ./docs/build/html:/usr/share/nginx/html
